name: minicomp_Anvar_Alex_Albert
channels:
  - conda-forge
  - anaconda
dependencies:
  - python
  - pip
  - numpy>=1.14
  - scikit-learn>=0.20.0
  - pandas>=0.22
  - matplotlib>=2.2.3
  - pip:
    - deepreplay
    - intuitiveml